language: go
go:
  - "1.13"
before_install:
  - export CODECOV_TOKEN="3179f100-4719-452a-a92f-a95ca10c0782"
  - export LIB=github.com/caigwatkin/go
before_script:
  - go vet -mod=vendor $LIB/...
  - go run github.com/mgechev/revive -formatter=stylish -config=./configs/revive.toml -exclude=./vendor/... ./...
script:
  - go test -mod=vendor -coverprofile=coverage.txt -covermode=atomic $LIB/...
after_success:
  - bash <(curl -s https://codecov.io/bash)
